apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gorax

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secrets.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  - api/pdb.yaml
  - worker/deployment.yaml
  - worker/hpa.yaml
  - worker/pdb.yaml
  - ingress.yaml

commonLabels:
  app: gorax
  managed-by: kustomize
